# NOTE: This docker-compose file is intended for development use.
# It is used to run required services for CoffeeBreak-Discord/bot to run
services:
  mariadb:
    image: mariadb:latest
    container_name: coffeebreak-development-mariadb
    env_file:
      - .mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - "./.devel-data/mariadb/data:/var/lib/mysql"
  redis:
    image: redis:latest
    container_name: coffeebreak-development-redis
    ports:
      - "6379:6379"
    volumes:
      - "./.devel-data/redis/data:/data"
version: "3"
