name: .NET build & test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3.0.2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.x
      - name: Cache NuGet packages
        uses: actions/cache@v3.0.8
        with:
          path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Restore project dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
