name: .NET build & test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.x
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity detailed
